[project]
name = "plane-project"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aerosandbox[full]>=4.2.8",
    "cadquery~=2.5.2",
    "ezdxf>=1.4.2",
    "numpy~=2.0.1",
    "shapely>=2.1.1",
]
